
export interface Connector {
    id: string;
    name: string;
    description: string;
    icon?: string;
    downloads?: string;
    type: 'web' | 'desktop' | 'mcp';
}

export const MOCK_CONNECTORS: Connector[] = [
    { id: 'candid', name: 'Candid', description: "Research nonprofits and funders using Candid's data", type: 'web' },
    { id: 'benevity', name: 'Benevity', description: "Find and engage with verified nonprofits", type: 'web' },
    { id: 'aws-marketplace', name: 'AWS Marketplace', description: "Discover, evaluate, and buy solutions for the cloud", type: 'web' },
    { id: 'n8n', name: 'n8n', description: "Access and run your n8n workflows", type: 'web' },
    { id: 'crypto-com', name: 'Crypto.com', description: "Real time prices, orders, charts, and more for crypto", type: 'web' },
    { id: 'godaddy', name: 'GoDaddy', description: "Search domains and check availability", type: 'web' },
    { id: 'honeycomb', name: 'Honeycomb', description: "Query and explore observability data and SLOs", type: 'web' },
    { id: 'fellow-ai', name: 'Fellow.ai', description: "Chat with your meetings to uncover actionable insights", type: 'web' },
    { id: 'cdata', name: 'CData Connect AI', description: "Managed MCP platform for 350 sources", type: 'web' },
    { id: 'visier', name: 'Visier', description: "Find people, productivity and business impact insights", type: 'web' },
    { id: 'kiwi', name: 'Kiwi.com', description: "Search flights in Claude", type: 'web' },
    { id: 'crossbeam', name: 'Crossbeam', description: "Explore partner data and ecosystem insights in Claude", type: 'web' },
    { id: 'activecampaign', name: 'ActiveCampaign', description: "Autonomous marketing to transform how you work", type: 'web' },
    { id: 'snowflake', name: 'Snowflake', description: "Retrieve both structured and unstructured data", type: 'web' },
    { id: 'hex', name: 'Hex', description: "Answer questions with the Hex agent", type: 'web' },
    { id: 'lseg', name: 'LSEG', description: "Access best in class data & analytics across a broad spectrum of asset classes.", type: 'web' },
    { id: 'mt-newswires', name: 'MT Newswires', description: "Trusted real-time global financial news provider", type: 'web' },
    { id: 'aiera', name: 'Aiera', description: "Live events, filings, company publications, and more", type: 'web' },
    { id: 'moodys', name: 'Moody\'s', description: "Risk insights, analytics, and decision intelligence", type: 'web' },
    { id: 'chronograph', name: 'Chronograph', description: "Interact with your Chronograph data directly in Claude", type: 'web' },
    { id: 'pitchbook', name: 'PitchBook Premium', description: "PitchBook data, embedded in the way you work.", type: 'web' },
    { id: 'trivago', name: 'Trivago', description: "Find your ideal hotel at the best price.", type: 'web' },
    { id: 'amplitude', name: 'Amplitude', description: "Search, access, and get insights on your Amplitude data", type: 'web' },
    { id: 'day-ai', name: 'Day AI', description: "Analyze & update CRM records", type: 'web' },
    { id: 'mermaid-chart', name: 'Mermaid Chart', description: "Validates & renders Mermaid diagrams as PNG images", type: 'web' },
    { id: 'pubmed', name: 'PubMed', description: "Search biomedical literature from PubMed", type: 'web' },
    { id: 'biorender', name: 'BioRender', description: "Search for and use scientific templates and icons", type: 'web' },
    { id: 'synapse', name: 'Synapse.org', description: "Search and metadata tools for Synapse scientific data", type: 'web' },
    { id: 'scholar-gateway', name: 'Scholar Gateway', description: "Enhance responses with scholarly research and citations", type: 'web' },
    { id: 'netsuite', name: 'NetSuite', description: "Connect Claude to NetSuite data for analysis & insights", type: 'web' },
    { id: 'databricks', name: 'Databricks', description: "Managed MCP servers with Unity Catalog and Mosaic AI", type: 'web' },
    { id: 'egnyte', name: 'Egnyte', description: "Securely access and analyze Egnyte content", type: 'web' },
    { id: 'coupler', name: 'Coupler.io', description: "Access business data from hundreds of sources", type: 'web' },
    { id: 'melon', name: 'Melon', description: "Browse music charts & your personalized music picks", type: 'web' },
    { id: 'clockwise', name: 'Clockwise', description: "Advanced scheduling and time management for work.", type: 'web' },
    { id: 'zoominfo', name: 'ZoomInfo', description: "Enrich contacts & accounts with GTM intelligence", type: 'web' },
    { id: 'figma', name: 'Figma', description: "Create better code with Figma context", type: 'web' },
    { id: 'learning-commons', name: 'Learning Commons', description: "K-12 standards, skills, and learning progressions", type: 'web' },
    { id: 'morningstar', name: 'Morningstar', description: "Up-to-date investment and market insights", type: 'web' },
    { id: 'sp-global', name: 'S&P Global', description: "Query a range of S&P Global datasets", type: 'web' },
    { id: 'ticket-tailor', name: 'Ticket Tailor', description: "Event platform for managing tickets, orders & more", type: 'web' },
    { id: 'aura', name: 'Aura', description: "Company intelligence & workforce analytics", type: 'web' },
    { id: 'jotform', name: 'Jotform', description: "Create forms & analyze submissions inside Claude", type: 'web' },
    { id: 'indeed', name: 'Indeed', description: "Search for jobs on Indeed", type: 'web' },
    { id: 'ramp', name: 'Ramp', description: "Search, access, and analyze your Ramp financial data", type: 'web' },
    { id: 'close', name: 'Close', description: "Connect Claude to Close CRM to securely access and act on your sales data", type: 'web' },
    { id: 'cloudinary', name: 'Cloudinary', description: "Manage, transform and deliver your images & videos", type: 'web' },
    { id: 'box', name: 'Box', description: "Search, access and get insights on your Box content", type: 'web' },
    { id: 'hugging-face', name: 'Hugging Face', description: "Access the Hugging Face Hub and thousands of Gradio Apps", type: 'web' },
    { id: 'stytch', name: 'Stytch', description: "Manage your Stytch Project", type: 'web' },
    { id: 'netlify', name: 'Netlify', description: "Create, deploy, manage, and secure websites on Netlify.", type: 'web' },
    { id: 'vercel', name: 'Vercel', description: "Analyze, debug, and manage projects and deployments", type: 'web' },
    { id: 'jam', name: 'Jam', description: "Record screen and collect automatic context for issues", type: 'web' },
    { id: 'asana', name: 'Asana', description: "Connect to Asana to coordinate tasks, projects, and goals", type: 'web' },
    { id: 'atlassian', name: 'Atlassian', description: "Access Jira & Confluence from Claude", type: 'web' },
    { id: 'canva', name: 'Canva', description: "Search, create, autofill, and export Canva designs", type: 'web' },
    { id: 'cloudflare', name: 'Cloudflare', description: "Build applications with compute, storage, and AI", type: 'web' },
    { id: 'daloopa', name: 'Daloopa', description: "Financial fundamental data and KPIs with hyperlinks", type: 'web' },
    { id: 'fireflies', name: 'Fireflies', description: "Analyze and generate insights from meeting transcripts", type: 'web' },
    { id: 'hubspot', name: 'HubSpot', description: "Chat with your CRM data to get personalized insights", type: 'web' },
    { id: 'intercom', name: 'Intercom', description: "Access to Intercom data for better customer insights", type: 'web' },
    { id: 'linear', name: 'Linear', description: "Manage issues, projects & team workflows in Linear", type: 'web' },
    { id: 'monday', name: 'monday.com', description: "Manage projects, boards, and workflows in monday.com", type: 'web' },
    { id: 'notion', name: 'Notion', description: "Connect your Notion workspace to search, update, and power workflows across tools", type: 'web' },
    { id: 'paypal', name: 'PayPal', description: "Access PayPal payments platform", type: 'web' },
    { id: 'plaid', name: 'Plaid', description: "Monitor, debug, and optimize your Plaid integration", type: 'web' },
    { id: 'sentry', name: 'Sentry', description: "Search, query, and debug errors intelligently", type: 'web' },
    { id: 'square', name: 'Square', description: "Search and manage transaction, merchant, and payment data", type: 'web' },
    { id: 'stripe', name: 'Stripe', description: "Payment processing and financial infrastructure tools", type: 'web' },
    { id: 'workato', name: 'Workato', description: "Automate workflows and connect your business apps", type: 'web' },
    { id: 'zapier', name: 'Zapier', description: "Automate workflows across thousands of apps via conversation", type: 'web' },
    { id: 'bitly', name: 'Bitly', description: "Shorten links, generate QR Codes, and track performance", type: 'web' },
    { id: 'benchling', name: 'Benchling', description: "Connect to R&D data, source experiments, and notebooks", type: 'web' },
    { id: 'pendo', name: 'Pendo', description: "Connect to Pendo for product and user insights", type: 'web' },
    { id: 'clickup', name: 'ClickUp', description: "Project management & collaboration for teams & agents", type: 'web' },
    { id: 'blockscout', name: 'Blockscout', description: "Access and analyze blockchain data", type: 'web' },

    // Desktop
    { id: 'windows-mcp', name: 'Windows-MCP', description: "MCP Server that enables Claude to interact with Windows OS", downloads: "777k", type: 'desktop' },
    { id: 'filesystem', name: 'Filesystem', description: "Let Claude access your filesystem to read and write files.", downloads: "533k", type: 'desktop' },
    { id: 'imessage', name: 'Read and Send iMessages', description: "Send, read, and manage messages through Apple's Messages app", downloads: "212k", type: 'desktop' },
    { id: 'chrome', name: 'Control Chrome', description: "Control Google Chrome browser tabs, windows, and navigation", downloads: "139k", type: 'desktop' },
    { id: 'figma-desktop', name: 'Figma', description: "Provides important design information and context when generating code from Figma design files", downloads: "108k", type: 'desktop' },
    { id: 'pdf-tools', name: 'PDF Tools', description: "Let Claude work with PDFs on your computer: read, analyze, fill forms, extract data", downloads: "94k", type: 'desktop' },
    { id: 'desktop-commander', name: 'Desktop Commander', description: "Build, explore, and automate on your local machine with access to files and terminal.", downloads: "89k", type: 'desktop' },
    { id: 'apple-notes', name: 'Read and Write Apple Notes', description: "Read, write, and manage notes in Apple Notes", downloads: "75k", type: 'desktop' },
    { id: 'context7', name: 'Context7', description: "Up-to-date Code Docs For Any Prompt", downloads: "70k", type: 'desktop' },
    { id: 'control-mac', name: 'Control your Mac', description: "Execute AppleScript to automate tasks on macOS.", downloads: "60k", type: 'desktop' },
    { id: 'tableau', name: 'Tableau', description: "An MCP server for Tableau", downloads: "45k", type: 'desktop' },
    { id: 'spotify', name: 'Spotify (AppleScript)', description: "Control Spotify via AppleScript", downloads: "35k", type: 'desktop' },
    { id: 'kapture', name: 'Kapture Browser Automation', description: "Control web browsers through the Model Context Protocol", downloads: "24k", type: 'desktop' },
    { id: 'postman', name: 'Postman MCP Server', description: "Connect your AI to your APIs on Postman.", downloads: "21k", type: 'desktop' },
    { id: 'airtable', name: 'Airtable MCP Server', description: "Read and write access to Airtable databases", downloads: "13k", type: 'desktop' },
    { id: 'b12', name: 'B12 Website Generator', description: "Create a website in seconds!", downloads: "11k", type: 'desktop' },
    { id: 'socket', name: 'Socket', description: "Socket MCP server for scanning dependencies", downloads: "10k", type: 'desktop' },
    { id: 'aws-api', name: 'AWS API MCP Server', description: "Manage AWS resources using AWS CLI commands", downloads: "9k", type: 'desktop' },
    { id: 'apify', name: 'Apify', description: "Extract data from any website", downloads: "8.7k", type: 'desktop' },
    { id: 'metabase', name: 'Metabase', description: "Access Metabase analytics data", downloads: "6.9k", type: 'desktop' },
];
